/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts -c wrangler.jsonc --include-runtime false` (hash: 5105a1cc5551e9383c7edbabf6faa45e)
declare namespace Cloudflare {
	interface Env {
		LOADER: WorkerLoader;
		AUTH_SESSION_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<Pick<Cloudflare.Env, "AUTH_SESSION_SECRET">> {}
}
