/**
 * This file is auto-generated. Do not edit this file manually.
 * To regenerate the schema, run:
 *   cd convex/betterAuth && npx @better-auth/cli generate -y
 *
 * To customize the schema, generate to an alternate file and import
 * the table definitions to your schema file. See
 * https://labs.convex.dev/better-auth/features/local-install#adding-custom-indexes.
 */
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export const tables = {
	user: defineTable({
		name: v.string(),
		email: v.string(),
		emailVerified: v.boolean(),
		image: v.optional(v.union(v.null(), v.string())),
		createdAt: v.number(),
		updatedAt: v.number(),
		userId: v.optional(v.union(v.null(), v.string())),
	})
		.index("email", ["email"])
		.index("userId", ["userId"]),
	session: defineTable({
		expiresAt: v.number(),
		token: v.string(),
		createdAt: v.number(),
		updatedAt: v.number(),
		ipAddress: v.optional(v.union(v.null(), v.string())),
		userAgent: v.optional(v.union(v.null(), v.string())),
		userId: v.string(),
		activeOrganizationId: v.optional(v.union(v.null(), v.string())),
	})
		.index("token", ["token"])
		.index("userId", ["userId"]),
	account: defineTable({
		accountId: v.string(),
		providerId: v.string(),
		userId: v.string(),
		accessToken: v.optional(v.union(v.null(), v.string())),
		refreshToken: v.optional(v.union(v.null(), v.string())),
		idToken: v.optional(v.union(v.null(), v.string())),
		accessTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
		refreshTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
		scope: v.optional(v.union(v.null(), v.string())),
		password: v.optional(v.union(v.null(), v.string())),
		createdAt: v.number(),
		updatedAt: v.number(),
	})
		.index("accountId", ["accountId"])
		.index("accountId_providerId", ["accountId", "providerId"])
		.index("userId", ["userId"]),
	verification: defineTable({
		identifier: v.string(),
		value: v.string(),
		expiresAt: v.number(),
		createdAt: v.number(),
		updatedAt: v.number(),
	})
		.index("expiresAt", ["expiresAt"])
		.index("identifier", ["identifier"]),
	jwks: defineTable({
		publicKey: v.string(),
		privateKey: v.string(),
		createdAt: v.number(),
		expiresAt: v.optional(v.union(v.null(), v.number())),
	}),
	organization: defineTable({
		name: v.string(),
		slug: v.string(),
		logo: v.optional(v.union(v.null(), v.string())),
		createdAt: v.number(),
		metadata: v.optional(v.union(v.null(), v.string())),
	}).index("slug", ["slug"]),
	member: defineTable({
		organizationId: v.string(),
		userId: v.string(),
		role: v.string(),
		createdAt: v.number(),
	})
		.index("organizationId", ["organizationId"])
		.index("userId", ["userId"]),
	invitation: defineTable({
		organizationId: v.string(),
		email: v.string(),
		role: v.optional(v.union(v.null(), v.string())),
		status: v.string(),
		expiresAt: v.number(),
		createdAt: v.number(),
		inviterId: v.string(),
	})
		.index("organizationId", ["organizationId"])
		.index("email", ["email"]),
	oauthApplication: defineTable({
		name: v.string(),
		icon: v.optional(v.union(v.null(), v.string())),
		metadata: v.optional(v.union(v.null(), v.string())),
		clientId: v.string(),
		clientSecret: v.optional(v.union(v.null(), v.string())),
		redirectUrls: v.string(),
		type: v.string(),
		disabled: v.optional(v.union(v.null(), v.boolean())),
		userId: v.optional(v.union(v.null(), v.string())),
		createdAt: v.number(),
		updatedAt: v.number(),
	})
		.index("clientId", ["clientId"])
		.index("userId", ["userId"]),
	oauthAccessToken: defineTable({
		accessToken: v.string(),
		refreshToken: v.string(),
		accessTokenExpiresAt: v.number(),
		refreshTokenExpiresAt: v.number(),
		clientId: v.string(),
		userId: v.optional(v.union(v.null(), v.string())),
		scopes: v.string(),
		createdAt: v.number(),
		updatedAt: v.number(),
	})
		.index("accessToken", ["accessToken"])
		.index("refreshToken", ["refreshToken"])
		.index("clientId", ["clientId"])
		.index("userId", ["userId"]),
	oauthConsent: defineTable({
		clientId: v.string(),
		userId: v.string(),
		scopes: v.string(),
		createdAt: v.number(),
		updatedAt: v.number(),
		consentGiven: v.boolean(),
	})
		.index("clientId", ["clientId"])
		.index("userId", ["userId"]),
	apikey: defineTable({
		configId: v.string(),
		name: v.optional(v.union(v.null(), v.string())),
		start: v.optional(v.union(v.null(), v.string())),
		referenceId: v.string(),
		prefix: v.optional(v.union(v.null(), v.string())),
		key: v.string(),
		refillInterval: v.optional(v.union(v.null(), v.number())),
		refillAmount: v.optional(v.union(v.null(), v.number())),
		lastRefillAt: v.optional(v.union(v.null(), v.number())),
		enabled: v.optional(v.union(v.null(), v.boolean())),
		rateLimitEnabled: v.optional(v.union(v.null(), v.boolean())),
		rateLimitTimeWindow: v.optional(v.union(v.null(), v.number())),
		rateLimitMax: v.optional(v.union(v.null(), v.number())),
		requestCount: v.optional(v.union(v.null(), v.number())),
		remaining: v.optional(v.union(v.null(), v.number())),
		lastRequest: v.optional(v.union(v.null(), v.number())),
		expiresAt: v.optional(v.union(v.null(), v.number())),
		createdAt: v.number(),
		updatedAt: v.number(),
		permissions: v.optional(v.union(v.null(), v.string())),
		metadata: v.optional(v.union(v.null(), v.string())),
	})
		.index("configId", ["configId"])
		.index("referenceId", ["referenceId"])
		.index("key", ["key"]),
};

const schema = defineSchema(tables);

export default schema;
